export const SHOW_MODAL = "SHOW_MODAL"
export const HIDE_MODAL = "HIDE_MODAL"
export const DESTROY_MODAL = "DESTROY_MODAL"
export const CHANGE_SIDEBAR = "CHANGE_SIDEBAR"



export const NETWORK_ERROR = "NETWORK_ERROR"
export const SHOW_NETWORK_MODAL = "SHOW_NETWORK_MODAL"




export const START_ACTION = "START_ACTION"
export const STOP_ACTION = "STOP_ACTION"




export const FETCH_CATEGORY = "FETCH_CATEGORY"
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS"
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE"





export const FETCH_LATEST_VIDEO = "FETCH_LATEST_VIDEO"
export const FETCH_LATEST_VIDEO_SUCCESS = "FETCH_LATEST_VIDEO_SUCCESS"
export const FETCH_LATEST_VIDEO_FAILURE = "FETCH_LATEST_VIDEO_FAILURE"




export const SIGN_IN = "SIGN_IN"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE"





export const SIGN_UP = "SIGN_UP"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"



export const FETCH_PUBLIC_PLANS = "FETCH_PUBLIC_PLANS"
export const FETCH_PUBLIC_PLANS_SUCCESS = "FETCH_PUBLIC_PLANS_SUCCESS"
export const FETCH_PUBLIC_PLANS_FAILURE = "FETCH_PUBLIC_PLANS_FAILURE"




export const FETCH_FAQ = "FETCH_FAQ"
export const FETCH_FAQ_SUCCESS = "FETCH_FAQ_SUCCESS"
export const FETCH_FAQ_FAILURE = "FETCH_FAQ_FAILURE"





export const FETCH_VIEWED_VIDEOS = "FETCH_VIEWED_VIDEOS"
export const FETCH_VIEWED_VIDEOS_SUCCESS = "FETCH_VIEWED_VIDEOS_SUCCESS"
export const FETCH_VIEWED_VIDEOS_FAILURE = "FETCH_VIEWED_VIDEOS_FAILURE"




export const LOADER_RESOURCES = "LOADER_RESOURCES"
export const LOADER_RESOURCES_SUCCESS = "LOADER_RESOURCES_SUCCESS"
export const LOADER_RESOURCES_FAILURE = "LOADER_RESOURCES_FAILURE"

